<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Soy</string>
	<key>fileTypes</key>
	<array>
		<string>soy</string>
	</array>
	<key>firstLineMatch</key>
	<string>\{\s*namespace\b</string>
	<key>foldingStartMarker</key>
	<string>\{\s*template\s+[^\}]*\}</string>
	<key>foldingStopMarker</key>
	<string>\{\s*/\s*template\s*\}</string>
	<key>name</key>
	<string>Soy</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#template</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#if</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment-line</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment-block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment-doc</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#call</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#css</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#param</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#print</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#msg</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#for</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#foreach</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#switch</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tag</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#element-any</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#element-other</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attribute-lookup</key>
		<dict>
			<key>begin</key>
			<string>(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.attribute-lookup.begin.soy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.attribute-lookup.end.soy</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#primitive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<key>call</key>
		<dict>
			<key>begin</key>
			<string>(\{/?)\s*(call|delcall)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.soy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.soy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.soy</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.call.soy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=call|delcall)\s+[\.\w]+</string>
					<key>name</key>
					<string>variable.parameter.soy</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.soy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.soy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(data)\s*(=)</string>
				</dict>
			</array>
		</dict>
		<key>comment-block</key>
		<dict>
			<key>begin</key>
			<string>(/\*)(?!\*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.soy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\*/)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.soy</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.soy</string>
		</dict>
		<key>comment-doc</key>
		<dict>
			<key>begin</key>
			<string>(/\*\*)(?!/)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.soy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\*/)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.soy</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.documentation.soy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.soy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.soy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(@param|@param\?)\s+(\w+)</string>
				</dict>
			</array>
		</dict>
		<key>comment-line</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.soy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.soy</string>
		</dict>
		<key>css</key>
		<dict>
			<key>begin</key>
			<string>(\{/?)\s*(css)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.soy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.soy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.soy</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.css.soy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(LITERAL|REFERENCE|BACKEND_SPECIFIC|GOOG)\b</string>
					<key>name</key>
					<string>support.constant.soy</string>
				</dict>
			</array>
		</dict>
		<key>element-any</key>
		<dict>
			<key>begin</key>
			<string>(&lt;)([a-zA-Z0-9:]++)(?=[^&gt;]*&gt;&lt;/\2&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.soy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.soy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;)(&lt;)(/)(\2)(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.soy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.soy meta.scope.between-tag-pair.soy</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.soy</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.soy</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.soy</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.any.soy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#element-contents</string>
				</dict>
			</array>
		</dict>
		<key>element-attribute</key>
		<dict>
			<key>match</key>
			<string>\b([a-zA-Z\-:]+)</string>
			<key>name</key>
			<string>entity.other.attribute-name.soy</string>
		</dict>
		<key>element-contents</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#element-string-quoted-double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#element-string-quoted-single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#element-attribute</string>
				</dict>
			</array>
		</dict>
		<key>element-other</key>
		<dict>
			<key>begin</key>
			<string>(&lt;/?)([a-zA-Z0-9:]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.soy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.other.soy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.soy</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.other.soy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#element-contents</string>
				</dict>
			</array>
		</dict>
		<key>element-string-quoted-double</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.soy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.soy</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.soy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
			</array>
		</dict>
		<key>element-string-quoted-single</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.soy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.soy</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.soy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
			</array>
		</dict>
		<key>embedded-code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped-char</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#if</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#call</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#css</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#param</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#print</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#msg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#for</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#foreach</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#switch</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag</string>
				</dict>
			</array>
		</dict>
		<key>escaped-char</key>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>constant.character.escape</string>
		</dict>
		<key>for</key>
		<dict>
			<key>begin</key>
			<string>(\{/?)\s*(for)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.soy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.soy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.soy</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.for.soy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bin\b</string>
					<key>name</key>
					<string>keyword.operator.soy</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\brange\b</string>
					<key>name</key>
					<string>support.function.soy</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#primitive</string>
				</dict>
			</array>
		</dict>
		<key>foreach</key>
		<dict>
			<key>begin</key>
			<string>(\{/?)\s*(foreach)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.soy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.soy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.soy</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.foreach.soy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bin\b</string>
					<key>name</key>
					<string>keyword.operator.soy</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
			</array>
		</dict>
		<key>function</key>
		<dict>
			<key>match</key>
			<string>\b(isFirst|isLast|index|hasData|length|keys|round|floor|ceiling|min|max|randomInt)\b</string>
			<key>name</key>
			<string>support.function.soy</string>
		</dict>
		<key>if</key>
		<dict>
			<key>begin</key>
			<string>(\{/?)\s*(if|elseif)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.soy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.soy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.soy</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.if.soy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<key>msg</key>
		<dict>
			<key>begin</key>
			<string>(\{/?)\s*(msg)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.soy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.soy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.soy</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.msg.soy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.soy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.soy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(meaning|desc)\s*(=)</string>
				</dict>
			</array>
		</dict>
		<key>namespace</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.soy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.soy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(namespace|delpackage)\s+([\w\.]+)</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>[\d]+</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>match</key>
			<string>==|!=|\band\b|\bor\b|\bnot\b|-|\+|(?&lt;!\{)/|\?:</string>
			<key>name</key>
			<string>keyword.operator.soy</string>
		</dict>
		<key>param</key>
		<dict>
			<key>begin</key>
			<string>(\{/?)\s*(param)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.soy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.soy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.soy</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.param.soy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.soy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.soy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b([\w]*)\s*(:)?</string>
				</dict>
			</array>
		</dict>
		<key>primitive</key>
		<dict>
			<key>match</key>
			<string>\b(null|false|true)\b</string>
			<key>name</key>
			<string>constant.language.soy</string>
		</dict>
		<key>print</key>
		<dict>
			<key>begin</key>
			<string>(\{/?)\s*(print)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.soy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.soy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.soy</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.print.soy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#print-parameter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#primitive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute-lookup</string>
				</dict>
			</array>
		</dict>
		<key>print-parameter</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\|</string>
					<key>name</key>
					<string>keyword.operator.soy</string>
				</dict>
				<dict>
					<key>match</key>
					<string>noAutoescape|id|escapeHtml|escapeJs|insertWorkBreaks|truncate</string>
					<key>name</key>
					<string>variable.parameter.soy</string>
				</dict>
			</array>
		</dict>
		<key>special-character</key>
		<dict>
			<key>match</key>
			<string>(\bsp\b|\bnil\b|\\r|\\n|\\t|\blb\b|\brb\b)</string>
			<key>name</key>
			<string>support.constant.soy</string>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-quoted-single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-quoted-double</string>
				</dict>
			</array>
		</dict>
		<key>string-quoted-double</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped-char</string>
				</dict>
			</array>
		</dict>
		<key>string-quoted-single</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped-char</string>
				</dict>
			</array>
		</dict>
		<key>switch</key>
		<dict>
			<key>begin</key>
			<string>(\{/?)\s*(switch|case)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.soy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.soy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.soy</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.switch.soy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<key>tag</key>
		<dict>
			<key>begin</key>
			<string>(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.soy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.soy</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#namespace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#special-character</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-simple</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute-lookup</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#primitive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#print-parameter</string>
				</dict>
			</array>
		</dict>
		<key>tag-simple</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=\{|\{/)\s*(literal|else|ifempty|default)\s*(?=\})</string>
			<key>name</key>
			<string>entity.name.tag.soy</string>
		</dict>
		<key>template</key>
		<dict>
			<key>begin</key>
			<string>(\{/?)\s*(template|deltemplate)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.soy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.soy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.soy</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.template.soy</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.soy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=template|deltemplate)\s+([\.\w]+)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.soy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.soy</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.soy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(private)\s*(=)\s*("true"|"false")</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.soy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.soy</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.quoted.single.soy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(private)\s*(=)\s*('true'|'false')</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.soy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.soy</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.soy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(autoescape)\s*(=)\s*("true"|"false"|"contextual")</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.soy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.soy</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.quoted.single.soy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(autoescape)\s*(=)\s*('true'|'false'|'contextual')</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>match</key>
			<string>\$[\w\.]+</string>
			<key>name</key>
			<string>variable.other.soy</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.soy</string>
	<key>uuid</key>
	<string>C56846DE-CB9A-4DB5-9D38-DC417DEA4D5F</string>
</dict>
</plist>
