<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>soy</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{template\s*\.\w+\s*\}</string>
	<key>foldingStopMarker</key>
	<string>\{\s*/\s*template\s*\}</string>
	<key>name</key>
	<string>SoyTemplate</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.soy</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>contentName</key>
			<string>comment.block.preprocessor</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.soy</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{template\s*\.(\w+)\s*\}</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.soy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\{\s*/\s*template\s*\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>id=".*"</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(namespace|if|else|foreach|ifempty|call|in)\b</string>
			<key>name</key>
			<string>keyword.control.soy</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.soy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\{template\s*\.(\w+)\s*\}</string>
			<key>name</key>
			<string>meta.function.soy</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.soy</string>
	<key>uuid</key>
	<string>C56846DE-CB9A-4DB5-9D38-DC417DEA4D5F</string>
</dict>
</plist>
