<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>soy</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{template\s*\.\w+[^\}]*\}</string>
	<key>foldingStopMarker</key>
	<string>\{\s*/\s*template\s*\}</string>
	<key>name</key>
	<string>SoyTemplate</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.soy</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*|&lt;!\-\-</string>
			<key>contentName</key>
			<string>comment.block.preprocessor</string>
			<key>end</key>
			<string>\*/|\-\-&gt;</string>
			<key>name</key>
			<string>comment.block.soy</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{(template)\s*\.(\w+)\s*\}</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.soy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.soy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\{\s*/\s*(template)\s*\}</string>
			<key>name</key>
			<string>meta.tmpl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#html_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#itl_message</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html_tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.soy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\{template\s*\.(\w+)[^\}]*\}</string>
			<key>name</key>
			<string>meta.function.soy</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>meta.text.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\$[\w_\.]+</string>
					<key>name</key>
					<string>variable.parameter.soy</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#itl_message</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[\{\}]</string>
					<key>name</key>
					<string>meta.soy.brache</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>[\{\}]</string>
			<key>name</key>
			<string>meta.soy.brache</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>double_quoted_string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.soy</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.soy</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.soy</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#itl_message</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#parameter</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>match</key>
							<string>.+?</string>
							<key>name</key>
							<string>constant.character.escape.soy</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>html_comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;\!\-\-</string>
					<key>contentName</key>
					<string>commment.block.preprocessor</string>
					<key>end</key>
					<string>\-\-&gt;</string>
					<key>name</key>
					<string>comment.block.soy</string>
				</dict>
			</array>
		</dict>
		<key>html_tag</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;</string>
					<key>end</key>
					<string>&gt;</string>
					<key>name</key>
					<string>tag.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#itl_message</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#parameter</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#double_quoted_string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#single_quoted_string</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>itl_message</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{msg.*?\}</string>
					<key>end</key>
					<string>\{/msg\}</string>
					<key>name</key>
					<string>string.other.soy</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(namespace|not|and|switch|case|default|sp|true|false|if|else|elseif|param|foreach|ifempty|call|in)\b</string>
					<key>name</key>
					<string>keyword.control.soy</string>
				</dict>
			</array>
		</dict>
		<key>parameter</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\$[\w_\.]+</string>
					<key>name</key>
					<string>variable.parameter.soy</string>
				</dict>
			</array>
		</dict>
		<key>single_quoted_string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.soy</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.soy</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.soy</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#itl_message</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#parameter</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>match</key>
							<string>.+?</string>
							<key>name</key>
							<string>constant.character.escape.soy</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.soy</string>
	<key>uuid</key>
	<string>C56846DE-CB9A-4DB5-9D38-DC417DEA4D5F</string>
</dict>
</plist>
